# Replace the "backend" object below with the snippet from DecapBridge. We need something here to get the CMS to work locally, but this alone won't work in production
backend:
  name: git-gateway
  branch: main

# Keep this to allow you to edit the cms locally
local_backend: true

# Change url to a link to the image you want to use, no file paths, must be a URL
logo:
  src: "https://www.senoweb.cz/assets/images/senoweb_og_logo_rounded.png"
  show_in_header: false

locale: "cs"

# Where should uploaded files be saved
media_folder: "src/assets/images/cms"

# Where should media be served, relative to the base of the built site
public_folder: "/assets/images/cms"

# Slug function configuration
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Decap CMS Collections
collections:
  # ===================== #
  # ===== AKTUALITY ===== #
  # ===================== #
  - label: "Aktuality"
    name: "aktuality"
    folder: "src/content/cms/aktuality"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    summary: "{{ title }} [{{ date | date('DD. MM. YYYY') }}]"
    editor:
      preview: true

    view_filters:
      - label: "Pardubice"
        field: "workplace"
        pattern: "Pardubice"

      - label: "Chrudim"
        field: "workplace"
        pattern: "Chrudim"

      - label: "Přelouč"
        field: "workplace"
        pattern: "Přelouč"

      - label: "Holice"
        field: "workplace"
        pattern: "Holice"

      - label: "Hlinsko v Čechách"
        field: "workplace"
        pattern: "Hlinsko v Čechách"

      - label: "Třemošnice"
        field: "workplace"
        pattern: "Třemošnice"

    view_groups:
      - label: "Pracoviště"
        field: "workplace"

    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }

      - label: "Pracoviště"
        name: "workplace"
        widget: "select"
        multiple: true
        required: true
        options:
          - { label: "Pardubice", value: "Pardubice" }
          - { label: "Chrudim", value: "Chrudim" }
          - { label: "Přelouč", value: "Přelouč" }
          - { label: "Holice", value: "Holice" }
          - { label: "Hlinsko v Čechách", value: "Hlinsko v Čechách" }
          - { label: "Třemošnice", value: "Třemošnice" }

      - { label: "Obsah", name: "body", widget: "markdown" }
      - {
          label: "Štítky",
          name: "tags",
          widget: "hidden",
          default: ["aktuality"],
        }

  # =================== #
  # ===== NOVINKY ===== #
  # =================== #
  - label: "Novinky"
    name: "novinky"
    folder: "src/content/cms/novinky"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    summary: "{{ title }} [{{ date | date('DD. MM. YYYY') }}]"
    editor:
      preview: true

    view_filters:
      - label: "Pardubice"
        field: "workplace"
        pattern: "Pardubice"

      - label: "Chrudim"
        field: "workplace"
        pattern: "Chrudim"

      - label: "Přelouč"
        field: "workplace"
        pattern: "Přelouč"

      - label: "Holice"
        field: "workplace"
        pattern: "Holice"

      - label: "Hlinsko v Čechách"
        field: "workplace"
        pattern: "Hlinsko v Čechách"

      - label: "Třemošnice"
        field: "workplace"
        pattern: "Třemošnice"

    view_groups:
      - label: "Pracoviště"
        field: "workplace"

    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }

      - label: "Pracoviště"
        name: "workplace"
        widget: "select"
        multiple: true
        required: true
        options:
          - { label: "Pardubice", value: "Pardubice" }
          - { label: "Chrudim", value: "Chrudim" }
          - { label: "Přelouč", value: "Přelouč" }
          - { label: "Holice", value: "Holice" }
          - { label: "Hlinsko v Čechách", value: "Hlinsko v Čechách" }
          - { label: "Třemošnice", value: "Třemošnice" }

      - {
          label: "Náhledový obrázek",
          name: "image",
          widget: "image",
          choose_url: false, # Only allow local images - for image optimization reasons
        }
      - {
          label: "Popis obrázku",
          name: "imageAlt",
          widget: "string",
          hint: "Popište, co je na obrázku. Slouží k validnímu SEO příspěvku.",
        }
      - { label: "Obsah", name: "body", widget: "markdown" }
      - {
          label: "Štítky",
          name: "tags",
          widget: "hidden",
          default: ["novinky"],
        }

  # ===================== #
  # ===== DOKUMENTY ===== #
  # ===================== #
  - label: "Dokumenty"
    name: "dokumenty"
    folder: "src/content/cms/dokumenty"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    summary: "{{ title }} [{{ date | date('DD. MM. YYYY') }}]"
    editor:
      preview: true

    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Popis", name: "description", widget: "text" }
      - { label: "Datum", name: "date", widget: "datetime" }

      - label: "Kategorie"
        name: "category"
        widget: "select"
        multiple: true
        required: true
        options:
          - { label: "Doporučené dokumenty", value: "Doporučené dokumenty" }
          - { label: "Pro rodiče a žáky", value: "Pro rodiče a žáky" }
          - { label: "Pro školy", value: "Pro školy" }
          - {
              label: "Interní předpisy a metodiky",
              value: "Interní předpisy a metodiky",
            }
          - {
              label: "Výroční zprávy a oficiální dokumenty",
              value: "Výroční zprávy a oficiální dokumenty",
            }
          - {
              label: "Archiv starších materiálů",
              value: "Archiv starších materiálů",
            }

      - { label: "Soubor", name: "url", widget: "file" }
      - {
          label: "Štítky",
          name: "tags",
          widget: "hidden",
          default: ["dokumenty"],
        }

  # ============================= #
  # ===== KRITICKÁ OZNÁMENÍ ===== #
  # ============================= #
  - label: "Kritická oznámení"
    name: "oznameni"
    folder: "src/content/cms/oznameni"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    summary: "{{ title }}"
    editor:
      preview: true

    view_filters:
      - label: "Aktivní oznámení"
        field: "enabled"
        pattern: true

      - label: "Pardubice"
        field: "workplace"
        pattern: "Pardubice"

      - label: "Chrudim"
        field: "workplace"
        pattern: "Chrudim"

      - label: "Přelouč"
        field: "workplace"
        pattern: "Přelouč"

      - label: "Holice"
        field: "workplace"
        pattern: "Holice"

      - label: "Hlinsko v Čechách"
        field: "workplace"
        pattern: "Hlinsko v Čechách"

      - label: "Třemošnice"
        field: "workplace"
        pattern: "Třemošnice"

    view_groups:
      - label: "Pracoviště"
        field: "workplace"

      - label: "Typ oznámení"
        field: "type"

    fields:
      - {
          label: "Název",
          name: "title",
          widget: "string",
          hint: "Interní název oznámení sloužící k identifikaci položky v administraci. Tento název se na webu nezobrazuje.",
        }
      - {
          label: "Text",
          name: "description",
          widget: "string",
          hint: "Krátký text, který je zobrazen v horní častí webu, pokud je oznámení aktivní.",
        }

      - label: "Pracoviště"
        name: "workplace"
        widget: "select"
        multiple: true
        required: true
        options:
          - { label: "Pardubice", value: "Pardubice" }
          - { label: "Chrudim", value: "Chrudim" }
          - { label: "Přelouč", value: "Přelouč" }
          - { label: "Holice", value: "Holice" }
          - { label: "Hlinsko v Čechách", value: "Hlinsko v Čechách" }
          - { label: "Třemošnice", value: "Třemošnice" }

      - label: "Typ"
        name: "type"
        widget: "select"
        multiple: false
        required: true
        hint: "Zvolený typ určuje barvu a vizuální zvýraznění banneru na webu."
        options:
          - { label: "Informace (modrá)", value: "info" }
          - { label: "Upozornění (oranžová)", value: "warning" }
          - { label: "Důležité oznámení (červená)", value: "danger" }
          - { label: "Potvrzení (zelená)", value: "success" }

      - {
          label: "Zobrazit oznámení",
          name: "enabled",
          widget: "boolean",
          required: false,
          hint: "V případě zakliknutí tohoto pole se oznámení zobrazuje na webu.",
        }
      - { label: "Obsah", name: "body", widget: "markdown", required: false }
      - {
          label: "Štítky",
          name: "tags",
          widget: "hidden",
          default: ["oznameni"],
        }

  # ====================== #
  # ===== PRACOVNÍCI ===== #
  # ====================== #
  - label: "Pracovníci"
    name: "pracovnici"
    folder: "src/content/cms/pracovnici"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    summary: "{{ title }}"
    editor:
      preview: true

    view_filters:
      - label: "Pardubice"
        field: "workplace"
        pattern: "Pardubice"

      - label: "Chrudim"
        field: "workplace"
        pattern: "Chrudim"

      - label: "Přelouč"
        field: "workplace"
        pattern: "Přelouč"

      - label: "Holice"
        field: "workplace"
        pattern: "Holice"

      - label: "Hlinsko v Čechách"
        field: "workplace"
        pattern: "Hlinsko v Čechách"

      - label: "Třemošnice"
        field: "workplace"
        pattern: "Třemošnice"

    fields:
      - {
          label: "Celé jméno",
          name: "title",
          widget: "string",
          hint: "Zadejte celé jméno včetně titulů. Slouží k zobrazení hodnoty v administraci.",
        }
      - {
          label: "Titul před jménem",
          name: "titleBefore",
          widget: "string",
          required: false,
        }
      - { label: "Jméno", name: "firstName", widget: "string" }
      - { label: "Příjmení", name: "lastName", widget: "string" }
      - {
          label: "Titul za jménem",
          name: "titleAfter",
          widget: "string",
          required: false,
        }

      - label: "Pracoviště"
        name: "workplace"
        widget: "select"
        multiple: true
        required: true
        options:
          - { label: "Pardubice", value: "Pardubice" }
          - { label: "Chrudim", value: "Chrudim" }
          - { label: "Přelouč", value: "Přelouč" }
          - { label: "Holice", value: "Holice" }
          - { label: "Hlinsko v Čechách", value: "Hlinsko v Čechách" }
          - { label: "Třemošnice", value: "Třemošnice" }

      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Telefon", name: "phone", widget: "string", required: false }
      - {
          label: "Fotografie",
          name: "image",
          widget: "image",
          choose_url: false, # Only allow local images - for image optimization reasons
          required: false,
        }
      - {
          label: "Štítky",
          name: "tags",
          widget: "hidden",
          default: ["pracovnici"],
        }
